-- MySQL Script generated by MySQL Workbench
-- Mon Nov 23 16:51:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema money_divider
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema money_divider
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `money_divider` DEFAULT CHARACTER SET utf8mb4 ;
USE `money_divider` ;

-- -----------------------------------------------------
-- Table `money_divider`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `money_divider`.`room` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `create_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `money_divider`.`money`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `money_divider`.`money` (
  `room_id` INT(11) NOT NULL,
  `token` CHAR(3) NOT NULL,
  `owner_id` INT(11) NOT NULL,
  `amount` INT(11) NOT NULL,
  `state` VARCHAR(20) NOT NULL,
  `create_date` DATETIME NOT NULL,
  PRIMARY KEY (`room_id`, `token`),
  CONSTRAINT `fk_money_room_id`
    FOREIGN KEY (`room_id`)
    REFERENCES `money_divider`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `money_divider`.`money_divide_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `money_divider`.`money_divide_info` (
  `money_room_id` INT(11) NOT NULL,
  `money_token` CHAR(3) NOT NULL,
  `seq` INT(11) NOT NULL,
  `amount` INT(11) NOT NULL,
  `create_date` DATETIME NOT NULL,
  `receive_user_id` INT(11) NULL DEFAULT NULL,
  `receive_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`money_room_id`, `money_token`, `seq`),
  INDEX `fk_money_divide_info_money1_idx` (`money_room_id` ASC, `money_token` ASC),
  CONSTRAINT `fk_money_divide_info_money1`
    FOREIGN KEY (`money_room_id` , `money_token`)
    REFERENCES `money_divider`.`money` (`room_id` , `token`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `money_divider`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `money_divider`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `create_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `money_divider`.`room_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `money_divider`.`room_member` (
  `room_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `join_date` DATETIME NOT NULL,
  PRIMARY KEY (`room_id`, `user_id`),
  INDEX `fk_room_member_user_id_idx` (`user_id` ASC),
  CONSTRAINT `fk_room_member_room_id`
    FOREIGN KEY (`room_id`)
    REFERENCES `money_divider`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room_member_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `money_divider`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
